 model:
  input_size: 784
  hidden_size: 128
  num_classes: 10

training:
  batch_size: 64
  num_epochs: 10
  learning_rate: 0.001

data:
  train_data_path: 'data/train.csv'
  test_data_path: 'data/test.csv'
